package com.composetest.core.designsystem.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF472D21)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF6D4F41)
val onPrimaryContainerLight = Color(0xFFFFF8F7)
val secondaryLight = Color(0xFF6B5B54)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFF5DFD6)
val onSecondaryContainerLight = Color(0xFF54453F)
val tertiaryLight = Color(0xFF393419)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFF5C5639)
val onTertiaryContainerLight = Color(0xFFFFF9F1)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFFF8F6)
val onBackgroundLight = Color(0xFF1E1B1A)
val surfaceLight = Color(0xFFFFF8F6)
val onSurfaceLight = Color(0xFF1E1B1A)
val surfaceVariantLight = Color(0xFFF0DFD8)
val onSurfaceVariantLight = Color(0xFF504440)
val outlineLight = Color(0xFF82746F)
val outlineVariantLight = Color(0xFFD4C3BD)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF33302E)
val inverseOnSurfaceLight = Color(0xFFF7EFEC)
val inversePrimaryLight = Color(0xFFE6BEAD)
val surfaceDimLight = Color(0xFFE0D8D6)
val surfaceBrightLight = Color(0xFFFFF8F6)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFFAF2EF)
val surfaceContainerLight = Color(0xFFF4ECEA)
val surfaceContainerHighLight = Color(0xFFEFE6E4)
val surfaceContainerHighestLight = Color(0xFFE9E1DE)

val primaryDark = Color(0xFFE6BEAD)
val onPrimaryDark = Color(0xFF432A1F)
val primaryContainerDark = Color(0xFF52372A)
val onPrimaryContainerDark = Color(0xFFF1C8B7)
val secondaryDark = Color(0xFFD7C2BA)
val onSecondaryDark = Color(0xFF3B2E28)
val secondaryContainerDark = Color(0xFF4B3D36)
val onSecondaryContainerDark = Color(0xFFE6D0C8)
val tertiaryDark = Color(0xFFD0C7A2)
val onTertiaryDark = Color(0xFF363017)
val tertiaryContainerDark = Color(0xFF433D22)
val onTertiaryContainerDark = Color(0xFFDAD1AB)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF161312)
val onBackgroundDark = Color(0xFFE9E1DE)
val surfaceDark = Color(0xFF161312)
val onSurfaceDark = Color(0xFFE9E1DE)
val surfaceVariantDark = Color(0xFF504440)
val onSurfaceVariantDark = Color(0xFFD4C3BD)
val outlineDark = Color(0xFF9C8E88)
val outlineVariantDark = Color(0xFF504440)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE9E1DE)
val inverseOnSurfaceDark = Color(0xFF33302E)
val inversePrimaryDark = Color(0xFF765749)
val surfaceDimDark = Color(0xFF161312)
val surfaceBrightDark = Color(0xFF3C3837)
val surfaceContainerLowestDark = Color(0xFF100E0C)
val surfaceContainerLowDark = Color(0xFF1E1B1A)
val surfaceContainerDark = Color(0xFF221F1E)
val surfaceContainerHighDark = Color(0xFF2D2928)
val surfaceContainerHighestDark = Color(0xFF383432)

val linkColor = Color(0xFF0078D4)

internal val lightColorScheme = lightColorScheme(
    primary = primaryLight,
    onPrimary = onPrimaryLight,
    primaryContainer = primaryContainerLight,
    onPrimaryContainer = onPrimaryContainerLight,
    secondary = secondaryLight,
    onSecondary = onSecondaryLight,
    secondaryContainer = secondaryContainerLight,
    onSecondaryContainer = onSecondaryContainerLight,
    tertiary = tertiaryLight,
    onTertiary = onTertiaryLight,
    tertiaryContainer = tertiaryContainerLight,
    onTertiaryContainer = onTertiaryContainerLight,
    error = errorLight,
    onError = onErrorLight,
    errorContainer = errorContainerLight,
    onErrorContainer = onErrorContainerLight,
    background = backgroundLight,
    onBackground = onBackgroundLight,
    surface = surfaceLight,
    onSurface = onSurfaceLight,
    surfaceVariant = surfaceVariantLight,
    onSurfaceVariant = onSurfaceVariantLight,
    outline = outlineLight,
    outlineVariant = outlineVariantLight,
    scrim = scrimLight,
    inverseSurface = inverseSurfaceLight,
    inverseOnSurface = inverseOnSurfaceLight,
    inversePrimary = inversePrimaryLight,
    surfaceDim = surfaceDimLight,
    surfaceBright = surfaceBrightLight,
    surfaceContainerLowest = surfaceContainerLowestLight,
    surfaceContainerLow = surfaceContainerLowLight,
    surfaceContainer = surfaceContainerLight,
    surfaceContainerHigh = surfaceContainerHighLight,
    surfaceContainerHighest = surfaceContainerHighestLight,
)

internal val darkColorScheme = darkColorScheme(
    primary = primaryDark,
    onPrimary = onPrimaryDark,
    primaryContainer = primaryContainerDark,
    onPrimaryContainer = onPrimaryContainerDark,
    secondary = secondaryDark,
    onSecondary = onSecondaryDark,
    secondaryContainer = secondaryContainerDark,
    onSecondaryContainer = onSecondaryContainerDark,
    tertiary = tertiaryDark,
    onTertiary = onTertiaryDark,
    tertiaryContainer = tertiaryContainerDark,
    onTertiaryContainer = onTertiaryContainerDark,
    error = errorDark,
    onError = onErrorDark,
    errorContainer = errorContainerDark,
    onErrorContainer = onErrorContainerDark,
    background = backgroundDark,
    onBackground = onBackgroundDark,
    surface = surfaceDark,
    onSurface = onSurfaceDark,
    surfaceVariant = surfaceVariantDark,
    onSurfaceVariant = onSurfaceVariantDark,
    outline = outlineDark,
    outlineVariant = outlineVariantDark,
    scrim = scrimDark,
    inverseSurface = inverseSurfaceDark,
    inverseOnSurface = inverseOnSurfaceDark,
    inversePrimary = inversePrimaryDark,
    surfaceDim = surfaceDimDark,
    surfaceBright = surfaceBrightDark,
    surfaceContainerLowest = surfaceContainerLowestDark,
    surfaceContainerLow = surfaceContainerLowDark,
    surfaceContainer = surfaceContainerDark,
    surfaceContainerHigh = surfaceContainerHighDark,
    surfaceContainerHighest = surfaceContainerHighestDark,
)
